(* generated by dune *)

(** @canonical Ocaml5_parser.Annot *)
module Annot = Ocaml5_parser__Annot

(** @canonical Ocaml5_parser.Arg_helper *)
module Arg_helper = Ocaml5_parser__Arg_helper

(** @canonical Ocaml5_parser.Ast_helper *)
module Ast_helper = Ocaml5_parser__Ast_helper

(** @canonical Ocaml5_parser.Ast_invariants *)
module Ast_invariants = Ocaml5_parser__Ast_invariants

(** @canonical Ocaml5_parser.Ast_iterator *)
module Ast_iterator = Ocaml5_parser__Ast_iterator

(** @canonical Ocaml5_parser.Ast_mapper *)
module Ast_mapper = Ocaml5_parser__Ast_mapper

(** @canonical Ocaml5_parser.Asttypes *)
module Asttypes = Ocaml5_parser__Asttypes

(** @canonical Ocaml5_parser.Attr_helper *)
module Attr_helper = Ocaml5_parser__Attr_helper

(** @canonical Ocaml5_parser.Binutils *)
module Binutils = Ocaml5_parser__Binutils

(** @canonical Ocaml5_parser.Btype *)
module Btype = Ocaml5_parser__Btype

(** @canonical Ocaml5_parser.Build_path_prefix_map *)
module Build_path_prefix_map = Ocaml5_parser__Build_path_prefix_map

(** @canonical Ocaml5_parser.Builtin_attributes *)
module Builtin_attributes = Ocaml5_parser__Builtin_attributes

(** @canonical Ocaml5_parser.CamlinternalMenhirLib *)
module CamlinternalMenhirLib = Ocaml5_parser__CamlinternalMenhirLib

(** @canonical Ocaml5_parser.Ccomp *)
module Ccomp = Ocaml5_parser__Ccomp

(** @canonical Ocaml5_parser.Clflags *)
module Clflags = Ocaml5_parser__Clflags

(** @canonical Ocaml5_parser.Cmi_format *)
module Cmi_format = Ocaml5_parser__Cmi_format

(** @canonical Ocaml5_parser.Cmt2annot *)
module Cmt2annot = Ocaml5_parser__Cmt2annot

(** @canonical Ocaml5_parser.Cmt_format *)
module Cmt_format = Ocaml5_parser__Cmt_format

(** @canonical Ocaml5_parser.Config *)
module Config = Ocaml5_parser__Config

(** @canonical Ocaml5_parser.Consistbl *)
module Consistbl = Ocaml5_parser__Consistbl

(** @canonical Ocaml5_parser.Ctype *)
module Ctype = Ocaml5_parser__Ctype

(** @canonical Ocaml5_parser.Datarepr *)
module Datarepr = Ocaml5_parser__Datarepr

(** @canonical Ocaml5_parser.Depend *)
module Depend = Ocaml5_parser__Depend

(** @canonical Ocaml5_parser.Diffing *)
module Diffing = Ocaml5_parser__Diffing

(** @canonical Ocaml5_parser.Diffing_with_keys *)
module Diffing_with_keys = Ocaml5_parser__Diffing_with_keys

(** @canonical Ocaml5_parser.Docstrings *)
module Docstrings = Ocaml5_parser__Docstrings

(** @canonical Ocaml5_parser.Env *)
module Env = Ocaml5_parser__Env

(** @canonical Ocaml5_parser.Envaux *)
module Envaux = Ocaml5_parser__Envaux

(** @canonical Ocaml5_parser.Errortrace *)
module Errortrace = Ocaml5_parser__Errortrace

(** @canonical Ocaml5_parser.Frontend *)
module Frontend = Ocaml5_parser__Frontend

(** @canonical Ocaml5_parser.Ident *)
module Ident = Ocaml5_parser__Ident

(** @canonical Ocaml5_parser.Identifiable *)
module Identifiable = Ocaml5_parser__Identifiable

(** @canonical Ocaml5_parser.Includeclass *)
module Includeclass = Ocaml5_parser__Includeclass

(** @canonical Ocaml5_parser.Includecore *)
module Includecore = Ocaml5_parser__Includecore

(** @canonical Ocaml5_parser.Includemod *)
module Includemod = Ocaml5_parser__Includemod

(** @canonical Ocaml5_parser.Includemod_errorprinter *)
module Includemod_errorprinter = Ocaml5_parser__Includemod_errorprinter

(** @canonical Ocaml5_parser.Int_replace_polymorphic_compare *)
module Int_replace_polymorphic_compare = Ocaml5_parser__Int_replace_polymorphic_compare

(** @canonical Ocaml5_parser.Lazy_backtrack *)
module Lazy_backtrack = Ocaml5_parser__Lazy_backtrack

(** @canonical Ocaml5_parser.Lexer *)
module Lexer = Ocaml5_parser__Lexer

(** @canonical Ocaml5_parser.Load_path *)
module Load_path = Ocaml5_parser__Load_path

(** @canonical Ocaml5_parser.Local_store *)
module Local_store = Ocaml5_parser__Local_store

(** @canonical Ocaml5_parser.Location *)
module Location = Ocaml5_parser__Location

(** @canonical Ocaml5_parser.Longident *)
module Longident = Ocaml5_parser__Longident

(** @canonical Ocaml5_parser.Misc *)
module Misc = Ocaml5_parser__Misc

(** @canonical Ocaml5_parser.Mtype *)
module Mtype = Ocaml5_parser__Mtype

(** @canonical Ocaml5_parser.Numbers *)
module Numbers = Ocaml5_parser__Numbers

(** @canonical Ocaml5_parser.Oprint *)
module Oprint = Ocaml5_parser__Oprint

(** @canonical Ocaml5_parser.Outcometree *)
module Outcometree = Ocaml5_parser__Outcometree

(** @canonical Ocaml5_parser.Parmatch *)
module Parmatch = Ocaml5_parser__Parmatch

(** @canonical Ocaml5_parser.Parse *)
module Parse = Ocaml5_parser__Parse

(** @canonical Ocaml5_parser.Parser *)
module Parser = Ocaml5_parser__Parser

(** @canonical Ocaml5_parser.Parsetree *)
module Parsetree = Ocaml5_parser__Parsetree

(** @canonical Ocaml5_parser.Path *)
module Path = Ocaml5_parser__Path

(** @canonical Ocaml5_parser.Patterns *)
module Patterns = Ocaml5_parser__Patterns

(** @canonical Ocaml5_parser.Persistent_env *)
module Persistent_env = Ocaml5_parser__Persistent_env

(** @canonical Ocaml5_parser.Pparse *)
module Pparse = Ocaml5_parser__Pparse

(** @canonical Ocaml5_parser.Pprintast *)
module Pprintast = Ocaml5_parser__Pprintast

(** @canonical Ocaml5_parser.Predef *)
module Predef = Ocaml5_parser__Predef

(** @canonical Ocaml5_parser.Primitive *)
module Primitive = Ocaml5_parser__Primitive

(** @canonical Ocaml5_parser.Printast *)
module Printast = Ocaml5_parser__Printast

(** @canonical Ocaml5_parser.Printpat *)
module Printpat = Ocaml5_parser__Printpat

(** @canonical Ocaml5_parser.Printtyp *)
module Printtyp = Ocaml5_parser__Printtyp

(** @canonical Ocaml5_parser.Printtyped *)
module Printtyped = Ocaml5_parser__Printtyped

(** @canonical Ocaml5_parser.Profile *)
module Profile = Ocaml5_parser__Profile

(** @canonical Ocaml5_parser.Rec_check *)
module Rec_check = Ocaml5_parser__Rec_check

(** @canonical Ocaml5_parser.Shape *)
module Shape = Ocaml5_parser__Shape

(** @canonical Ocaml5_parser.Signature_group *)
module Signature_group = Ocaml5_parser__Signature_group

(** @canonical Ocaml5_parser.Strongly_connected_components *)
module Strongly_connected_components = Ocaml5_parser__Strongly_connected_components

(** @canonical Ocaml5_parser.Stypes *)
module Stypes = Ocaml5_parser__Stypes

(** @canonical Ocaml5_parser.Subst *)
module Subst = Ocaml5_parser__Subst

(** @canonical Ocaml5_parser.Syntaxerr *)
module Syntaxerr = Ocaml5_parser__Syntaxerr

(** @canonical Ocaml5_parser.Targetint *)
module Targetint = Ocaml5_parser__Targetint

(** @canonical Ocaml5_parser.Tast_iterator *)
module Tast_iterator = Ocaml5_parser__Tast_iterator

(** @canonical Ocaml5_parser.Tast_mapper *)
module Tast_mapper = Ocaml5_parser__Tast_mapper

(** @canonical Ocaml5_parser.Terminfo *)
module Terminfo = Ocaml5_parser__Terminfo

(** @canonical Ocaml5_parser.Type_immediacy *)
module Type_immediacy = Ocaml5_parser__Type_immediacy

(** @canonical Ocaml5_parser.Typeclass *)
module Typeclass = Ocaml5_parser__Typeclass

(** @canonical Ocaml5_parser.Typecore *)
module Typecore = Ocaml5_parser__Typecore

(** @canonical Ocaml5_parser.Typedecl *)
module Typedecl = Ocaml5_parser__Typedecl

(** @canonical Ocaml5_parser.Typedecl_immediacy *)
module Typedecl_immediacy = Ocaml5_parser__Typedecl_immediacy

(** @canonical Ocaml5_parser.Typedecl_properties *)
module Typedecl_properties = Ocaml5_parser__Typedecl_properties

(** @canonical Ocaml5_parser.Typedecl_separability *)
module Typedecl_separability = Ocaml5_parser__Typedecl_separability

(** @canonical Ocaml5_parser.Typedecl_unboxed *)
module Typedecl_unboxed = Ocaml5_parser__Typedecl_unboxed

(** @canonical Ocaml5_parser.Typedecl_variance *)
module Typedecl_variance = Ocaml5_parser__Typedecl_variance

(** @canonical Ocaml5_parser.Typedtree *)
module Typedtree = Ocaml5_parser__Typedtree

(** @canonical Ocaml5_parser.Typemod *)
module Typemod = Ocaml5_parser__Typemod

(** @canonical Ocaml5_parser.Types *)
module Types = Ocaml5_parser__Types

(** @canonical Ocaml5_parser.Typetexp *)
module Typetexp = Ocaml5_parser__Typetexp

(** @canonical Ocaml5_parser.Untypeast *)
module Untypeast = Ocaml5_parser__Untypeast

(** @canonical Ocaml5_parser.Warnings *)
module Warnings = Ocaml5_parser__Warnings

(** @canonical Ocaml5_parser.Zint *)
module Zint = Ocaml5_parser__Zint

(** @canonical Ocaml5_parser.Zstring *)
module Zstring = Ocaml5_parser__Zstring

(** @canonical Ocaml5_parser.Zsys *)
module Zsys = Ocaml5_parser__Zsys
